apiVersion: apps/v1
kind: Deployment
metadata:
  name: cool-counter-web
  labels:
    app: cool-counter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cool-counter
  template:
    metadata:
      labels:
        app: cool-counter
    spec:
      containers:
      - name: cool-counter
        image: cool-counter
        imagePullPolicy: Never
        ports:
        - containerPort: 4567
        env:
          - name: REDIS_HOST
            value: $(COOL_COUNTER_REDIS_SERVICE_HOST)
