apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cool-counter-ingress
  namespace: cool-namespace
  annotations:
    kubernetes.io/ingressClassName: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /ping
        backend:
          serviceName: cool-counter-web
          servicePort: 4567
      - path: /
        backend:
          serviceName: cool-counter-web
          servicePort: 4567 
