apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cool-counter-ingress
  namespace: cool-namespace
  annotations:
    kubernetes.io/ingressClassName: "nginx"
spec:
  backend:
    serviceName: cool-counter-web
    servicePort: 4567
