apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cool-counter-ingress
  namespace: cool-namespace
  annotations:
    kubernetes.io/ingressClassName: "nginx"
spec:
  defaultBackend:
    service:
      name: cool-counter-web
      port: 
        number: 4567
